language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"

cache:
  pip: true
  directories:
    - $HOME/.cache/pypoetry

install:
  - pip install poetry --pre
  - poetry install -v

script: pytest -q tests/
